<?php
/**
 * Created by PhpStorm.
 * User: daniel
 * Date: 16.12.16
 * Time: 02:29
 */

namespace AppBundle\Command;


use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\DBAL\Connection;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Helper\ProgressBar;

class FixtureCommand extends ContainerAwareCommand
{
    /**
     * @var Connection
     */
    private $conn;
    private $n,$l;

    protected function configure()
    {
        $this->setName('app:fixture:load')
        ->addArgument('table',InputArgument::REQUIRED, 'Name of table')
            ->addArgument('N',InputArgument::OPTIONAL)
            ->addArgument('L')
        ->addOption('append');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        switch ($input->getArgument('table')) {
            case 'minor':
                $progress = new ProgressBar($output, $this->n*$this->l);
                $progress->setFormat('very_verbose');
                $progress->start();
                $progress->setRedrawFrequency(25);

                for($i=1;$i<=$this->n;$i++){
                    $this->conn->delete('minor_'.$i,[1=>1]);
                    for($j=1;$j<=$this->l;$j++){
                        $this->conn->insert('minor_'.$i, array('id' => $j));
                        $progress->advance();
                    }
                }

                $progress->finish();
                $output->writeln("\n".'Created <info>'.$this->l.'</info> rows in <info>'.$this->n.'</info> tables. In sum <info>'.$this->l*$this->n.'</info> inserts.');
                break;
            case 'major':
        break;
            default:
                $output->writeln('Please chose table:');
                $output->writeln(sprintf('    <info>%s (main|minor)</info> to execute the command', $this->getName()));
        }
    }

//    protected function interact(InputInterface $input, OutputInterface $output)
//    {
//        parent::interact($input, $output); // TODO: Change the autogenerated stub
//    }

    protected function initialize(InputInterface $input, OutputInterface $output)
    {
//        var_dump($input);
//        var_dump($input->getArgument('table'));
//        var_dump($input->getArgument('L'));die();

        $this->conn = $this->getContainer()->get('doctrine')->getConnection();
        $this->n = $input->getArgument('N') ?: $this->getContainer()->getParameter('N');
        $this->l = $input->getArgument('L') ?: $this->getContainer()->getParameter('L');
    }

}